### ISSUE TITLE
OCF version 1.1

### ISSUE THREAD

**Issue by marxsk** [ClusterLabs/OCF-spec#13]
I believe that we are ready for OCF 1.1. Current, -next, version can validate existing resource agents (without additional notifications).

**Comment by krig** [comment]
Sounds good to me!

**Comment by kgaillot** [comment]
Created PR #14 as a basis for changes to bring to wider discussion. If that's unobjectionable, we can then do PRs to bring in the actual desired changes, and ask for feedback on the mailing lists

**Comment by marxsk** [comment]
@kgaillot Do you want to announce it in mailing lists? I will two weeks afterwards if there are any objections.

**Comment by kgaillot** [comment]
I will have a few changes in wording I'd like to see for 1.1, so after #14 is merged, I'll make a new request for list discussion.

**Comment by kgaillot** [comment]
Time flies ... but PR #16 is open for the wording changes.

**Comment by krig** [comment]
Time flies indeed :/ I hope to find some time to comment on these changes and maybe make some proposals myself soon. Great initiative to get this going! :+1:

**Comment by kgaillot** [comment]
The OCF RA API 1.1 standard was released in March 2021
